pool:
  vmImage: ubuntu-latest

steps:
- task: getConjureSecretSC@0
  inputs:
    ConjurService: 'Test-Connect'
    Project: 'TestProject'
- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET1: $(SECRET1)"
    echo "$(SECRET1)" | sed 's/./& /g'
