pool:
  vmImage: windows-latest

steps:
- task: build-task@0
  inputs:
    ConjurService: 'Test-Connect'

- powershell: |
    gci env:
    "Secrets retrieved:"
    echo "  SECRET1: $(SECRET1)"
    echo "$(SECRET1)" | sed 's/./& /g'
