pool:
  vmImage: ubuntu-latest

steps:
- task: build-task@0
  inputs:
    ConjurService: 'Test-Connect'
- task: GetConjurSecret@1
  inputs:
    ConjurService: 'Test-Connect'

- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET1: $(SECRET1)"
    echo "$(SECRET1)" | sed 's/./& /g'

#- powershell: echo $env:SECRET1