pool:
  vmImage: ubuntu-latest

steps:
- task: getConjureSecret@0
  inputs:
    ConjurService: 'Test-Connect'
- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET1: $(SECRET1)"
    echo "$(SECRET1)" | sed 's/./& /g'
