pool:
  name: 'default'

steps:

- task: GetConjurSecret@1
  inputs:
    conjurApplianceURL: 'https://conjur-azure-devops.eastus.cloudapp.azure.com'
    conjurAccount: 'conjur-azure'
    conjurUsername: 'admin'
    conjurAPIKey: 'Cyber@Ark123!'
    ignoreSSL: true

- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET1: $(SECRET1)"
    echo "$(SECRET1)" | sed 's/./& /g'
    echo "  SECRET2: $(SECRET2)"
    echo "$(SECRET2)" | sed 's/./& /g'
