pool: Default

#pool:
#  vmImage: windows-latest

steps:
- task: getConjureSecretSC-Dev@0
  inputs:
    ConjurService: 'Test-SSL'

- powershell: |
    "Secrets retrieved:"
    echo "  SECRET1: $(SECRET1)"
    echo "$(SECRET1)" | sed 's/./& /g'
